Repository MateusNhoato/ImaPay, pull requests merged in 2023-04, with the labels that each got.

#45 TopTitle component
  react/package-lock.json
  react/src/App.jsx
  react/src/assets/img/Logotipo_Oficial.svg
  react/src/components/TopTitle/TopTitle.css
  react/src/components/TopTitle/TopTitle.jsx
Labels: enhancement

#66 add transfer-page
  react/src/App.css
  react/src/App.jsx
  react/src/components/Form/Form.css
  react/src/components/Form/Form.jsx
  react/src/components/InfoCardComponent/InfoCardComponent.jsx
  react/src/components/Input/Input.css
  react/src/components/NavBar/NavBar.css
  react/src/pages/transfer_page/TransferPage.css
  react/src/pages/transfer_page/TransferPage.jsx
Labels: feature

#68 Transfer page
  react/src/components/Button/Button.css
  react/src/components/Form/Form.css
  react/src/components/Form/Form.jsx
  react/src/pages/transfer_page/TransferPage.jsx
Labels: enhancement

#72 feat: adding password page
  react/src/App.jsx
  react/src/pages/password/PasswordPage.css
  react/src/pages/password/PasswordPage.jsx
Labels: feature

#74 ajustes gerais
  react/src/App.css
  react/src/App.jsx
  react/src/components/Form/Form.css
  react/src/components/Form/Form.jsx
  react/src/components/InfoCardComponent/InfoCardComponent.css
  react/src/components/NavBar/NavBar.css
  react/src/pages/CompletedTransfer/CompletedTransfer.css
  react/src/pages/CompletedTransfer/CompletedTransfer.jsx
  react/src/pages/home/index.jsx
  react/src/pages/home/styles.css
  react/src/pages/password/PasswordPage.css
  react/src/pages/register/index.jsx
  react/src/pages/register/styles.css
  react/src/pages/transfer_page/TransferPage.jsx
Labels: enhancement

#75 Update App.jsx
  react/src/App.jsx
Labels: enhancement

#107 Integracao front back saldo
  src/pages/balance_page/index.jsx
Labels: feature

#110 fix balancePage
  src/pages/balance_page/index.jsx
Labels: bug
